# Form implementation generated from reading ui file 'drilling_zone.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DrillingZonePage(object):
    def setupUi(self, DrillingZonePage):
        DrillingZonePage.setObjectName("DrillingZonePage")
        DrillingZonePage.resize(530, 530)
        self.grp_map_zone = QtWidgets.QGroupBox(parent=DrillingZonePage)
        self.grp_map_zone.setGeometry(QtCore.QRect(20, 30, 490, 480))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.grp_map_zone.setFont(font)
        self.grp_map_zone.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(250, 252, 253);\n"
"    border: 1px solid #d0dee9; \n"
"    /* border-radius: 6px; */\n"
"    /*margin-top: -40px; /* отступ сверху для текста заголовка */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left: 25px;          /* отступ слева */\n"
"    top: 10px;          /* поднимаем текст, чтобы не пересекался с рамкой */\n"
"    /*background-color: white; /* фон под заголовком, чтобы \"перебить\" рамку */\n"
"    /*padding: 0 4px; */\n"
"    font-weight: 600;\n"
"}")
        self.grp_map_zone.setFlat(False)
        self.grp_map_zone.setObjectName("grp_map_zone")
        self.horizontalLayoutWidget_39 = QtWidgets.QWidget(parent=self.grp_map_zone)
        self.horizontalLayoutWidget_39.setGeometry(QtCore.QRect(20, 50, 421, 41))
        self.horizontalLayoutWidget_39.setObjectName("horizontalLayoutWidget_39")
        self.hlPercentTop = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_39)
        self.hlPercentTop.setContentsMargins(0, 0, 10, 0)
        self.hlPercentTop.setSpacing(30)
        self.hlPercentTop.setObjectName("hlPercentTop")
        self.lblPercentTop = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_39)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblPercentTop.setFont(font)
        self.lblPercentTop.setWordWrap(True)
        self.lblPercentTop.setObjectName("lblPercentTop")
        self.hlPercentTop.addWidget(self.lblPercentTop)
        self.lePercentTop = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_39)
        self.lePercentTop.setObjectName("lePercentTop")
        self.hlPercentTop.addWidget(self.lePercentTop)
        self.hlPercentTop.setStretch(0, 15)
        self.hlPercentTop.setStretch(1, 12)
        self.horizontalLayoutWidget_40 = QtWidgets.QWidget(parent=self.grp_map_zone)
        self.horizontalLayoutWidget_40.setGeometry(QtCore.QRect(20, 100, 421, 41))
        self.horizontalLayoutWidget_40.setObjectName("horizontalLayoutWidget_40")
        self.hlMinRadius = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_40)
        self.hlMinRadius.setContentsMargins(0, 0, 10, 0)
        self.hlMinRadius.setSpacing(30)
        self.hlMinRadius.setObjectName("hlMinRadius")
        self.lblMinRadius = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_40)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMinRadius.setFont(font)
        self.lblMinRadius.setWordWrap(True)
        self.lblMinRadius.setObjectName("lblMinRadius")
        self.hlMinRadius.addWidget(self.lblMinRadius)
        self.leMinRadius = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_40)
        self.leMinRadius.setObjectName("leMinRadius")
        self.hlMinRadius.addWidget(self.leMinRadius)
        self.hlMinRadius.setStretch(0, 15)
        self.hlMinRadius.setStretch(1, 12)
        self.horizontalLayoutWidget_41 = QtWidgets.QWidget(parent=self.grp_map_zone)
        self.horizontalLayoutWidget_41.setGeometry(QtCore.QRect(19, 150, 421, 41))
        self.horizontalLayoutWidget_41.setObjectName("horizontalLayoutWidget_41")
        self.hlSensitivity = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_41)
        self.hlSensitivity.setContentsMargins(0, 0, 10, 0)
        self.hlSensitivity.setSpacing(30)
        self.hlSensitivity.setObjectName("hlSensitivity")
        self.lblSensitivity = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_41)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSensitivity.setFont(font)
        self.lblSensitivity.setWordWrap(True)
        self.lblSensitivity.setObjectName("lblSensitivity")
        self.hlSensitivity.addWidget(self.lblSensitivity)
        self.leSensitivity = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_41)
        self.leSensitivity.setObjectName("leSensitivity")
        self.hlSensitivity.addWidget(self.leSensitivity)
        self.hlSensitivity.setStretch(0, 15)
        self.hlSensitivity.setStretch(1, 12)
        self.horizontalLayoutWidget_42 = QtWidgets.QWidget(parent=self.grp_map_zone)
        self.horizontalLayoutWidget_42.setGeometry(QtCore.QRect(20, 200, 421, 41))
        self.horizontalLayoutWidget_42.setObjectName("horizontalLayoutWidget_42")
        self.hlProfitCumOil = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_42)
        self.hlProfitCumOil.setContentsMargins(0, 0, 10, 0)
        self.hlProfitCumOil.setSpacing(30)
        self.hlProfitCumOil.setObjectName("hlProfitCumOil")
        self.lblProfitCumOil = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_42)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblProfitCumOil.setFont(font)
        self.lblProfitCumOil.setWordWrap(True)
        self.lblProfitCumOil.setObjectName("lblProfitCumOil")
        self.hlProfitCumOil.addWidget(self.lblProfitCumOil)
        self.leProfitCumOil = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_42)
        self.leProfitCumOil.setObjectName("leProfitCumOil")
        self.hlProfitCumOil.addWidget(self.leProfitCumOil)
        self.hlProfitCumOil.setStretch(0, 15)
        self.hlProfitCumOil.setStretch(1, 12)

        self.retranslateUi(DrillingZonePage)
        QtCore.QMetaObject.connectSlotsByName(DrillingZonePage)

    def retranslateUi(self, DrillingZonePage):
        _translate = QtCore.QCoreApplication.translate
        DrillingZonePage.setWindowTitle(_translate("DrillingZonePage", "Form"))
        self.grp_map_zone.setTitle(_translate("DrillingZonePage", "Параметры перспективных зон"))
        self.lblPercentTop.setText(_translate("DrillingZonePage", "Процент лучших точек для кластеризации, %"))
        self.lePercentTop.setText(_translate("DrillingZonePage", "30"))
        self.lblMinRadius.setText(_translate("DrillingZonePage", "Минимальный радиус зоны для бурения, м"))
        self.leMinRadius.setText(_translate("DrillingZonePage", "300"))
        self.lblSensitivity.setText(_translate("DrillingZonePage", "Чувствительность к качеству зоны бурения, %"))
        self.leSensitivity.setText(_translate("DrillingZonePage", "70"))
        self.lblProfitCumOil.setText(_translate("DrillingZonePage", "Минимальные запасы на скважину, тыс.т"))
        self.leProfitCumOil.setText(_translate("DrillingZonePage", "30"))
