# Form implementation generated from reading ui file 'economy.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EconomyPage(object):
    def setupUi(self, EconomyPage):
        EconomyPage.setObjectName("EconomyPage")
        EconomyPage.resize(530, 530)
        self.grp_economy = QtWidgets.QGroupBox(parent=EconomyPage)
        self.grp_economy.setGeometry(QtCore.QRect(20, 40, 490, 480))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.grp_economy.setFont(font)
        self.grp_economy.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(250, 252, 253);\n"
"    border: 1px solid #d0dee9; \n"
"    /* border-radius: 6px; */\n"
"    /*margin-top: -40px; /* отступ сверху для текста заголовка */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left: 25px;          /* отступ слева */\n"
"    top: 10px;          /* поднимаем текст, чтобы не пересекался с рамкой */\n"
"    /*background-color: white; /* фон под заголовком, чтобы \"перебить\" рамку */\n"
"    /*padding: 0 4px; */\n"
"    font-weight: 600;\n"
"}")
        self.grp_economy.setObjectName("grp_economy")
        self.horizontalLayoutWidget_45 = QtWidgets.QWidget(parent=self.grp_economy)
        self.horizontalLayoutWidget_45.setGeometry(QtCore.QRect(20, 130, 421, 41))
        self.horizontalLayoutWidget_45.setObjectName("horizontalLayoutWidget_45")
        self.hlStartDate = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_45)
        self.hlStartDate.setContentsMargins(0, 0, 10, 0)
        self.hlStartDate.setSpacing(55)
        self.hlStartDate.setObjectName("hlStartDate")
        self.lblStartDate = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_45)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblStartDate.setFont(font)
        self.lblStartDate.setWordWrap(True)
        self.lblStartDate.setObjectName("lblStartDate")
        self.hlStartDate.addWidget(self.lblStartDate)
        self.leStartDate = QtWidgets.QDateEdit(parent=self.horizontalLayoutWidget_45)
        self.leStartDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.leStartDate.setDate(QtCore.QDate(2025, 1, 1))
        self.leStartDate.setObjectName("leStartDate")
        self.hlStartDate.addWidget(self.leStartDate)
        self.hlStartDate.setStretch(0, 12)
        self.hlStartDate.setStretch(1, 10)
        self.horizontalLayoutWidget_46 = QtWidgets.QWidget(parent=self.grp_economy)
        self.horizontalLayoutWidget_46.setGeometry(QtCore.QRect(20, 170, 421, 41))
        self.horizontalLayoutWidget_46.setObjectName("horizontalLayoutWidget_46")
        self.hlNumDays = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_46)
        self.hlNumDays.setContentsMargins(0, 0, 10, 0)
        self.hlNumDays.setSpacing(55)
        self.hlNumDays.setObjectName("hlNumDays")
        self.lblNumDays = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_46)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblNumDays.setFont(font)
        self.lblNumDays.setScaledContents(True)
        self.lblNumDays.setWordWrap(True)
        self.lblNumDays.setObjectName("lblNumDays")
        self.hlNumDays.addWidget(self.lblNumDays)
        self.leNumDays = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_46)
        self.leNumDays.setObjectName("leNumDays")
        self.hlNumDays.addWidget(self.leNumDays)
        self.hlNumDays.setStretch(0, 12)
        self.hlNumDays.setStretch(1, 10)
        self.chkCalcEconomy = QtWidgets.QCheckBox(parent=self.grp_economy)
        self.chkCalcEconomy.setGeometry(QtCore.QRect(20, 50, 250, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chkCalcEconomy.setFont(font)
        self.chkCalcEconomy.setObjectName("chkCalcEconomy")
        self.horizontalLayoutWidget_47 = QtWidgets.QWidget(parent=self.grp_economy)
        self.horizontalLayoutWidget_47.setGeometry(QtCore.QRect(20, 80, 421, 41))
        self.horizontalLayoutWidget_47.setObjectName("horizontalLayoutWidget_47")
        self.hlEconomy = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_47)
        self.hlEconomy.setContentsMargins(0, 0, 10, 0)
        self.hlEconomy.setSpacing(55)
        self.hlEconomy.setObjectName("hlEconomy")
        self.lblEconomy = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_47)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblEconomy.setFont(font)
        self.lblEconomy.setWordWrap(True)
        self.lblEconomy.setObjectName("lblEconomy")
        self.hlEconomy.addWidget(self.lblEconomy)
        self.leEconomy = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_47)
        self.leEconomy.setObjectName("leEconomy")
        self.hlEconomy.addWidget(self.leEconomy)
        self.btnEconomy = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_47)
        self.btnEconomy.setObjectName("btnEconomy")
        self.hlEconomy.addWidget(self.btnEconomy)

        self.retranslateUi(EconomyPage)
        QtCore.QMetaObject.connectSlotsByName(EconomyPage)

    def retranslateUi(self, EconomyPage):
        _translate = QtCore.QCoreApplication.translate
        EconomyPage.setWindowTitle(_translate("EconomyPage", "Form"))
        self.grp_economy.setTitle(_translate("EconomyPage", "Экономика"))
        self.lblStartDate.setText(_translate("EconomyPage", "Дата начала расчёта денежного потока"))
        self.lblNumDays.setText(_translate("EconomyPage", "Количество дней в месяце"))
        self.leNumDays.setText(_translate("EconomyPage", "29"))
        self.chkCalcEconomy.setText(_translate("EconomyPage", "Расчёт экономических показателей"))
        self.lblEconomy.setText(_translate("EconomyPage", "Экономика"))
        self.btnEconomy.setText(_translate("EconomyPage", "Выбрать файл"))
