# Form implementation generated from reading ui file 'initial_data.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InitialDataPage(object):
    def setupUi(self, InitialDataPage):
        InitialDataPage.setObjectName("InitialDataPage")
        InitialDataPage.resize(530, 530)
        self.grp_initial_data = QtWidgets.QGroupBox(parent=InitialDataPage)
        self.grp_initial_data.setGeometry(QtCore.QRect(20, 30, 490, 480))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.grp_initial_data.setFont(font)
        self.grp_initial_data.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(250, 252, 253);\n"
"    border: 1px solid #d0dee9; \n"
"    /* border-radius: 6px; */\n"
"    /*margin-top: -40px; /* отступ сверху для текста заголовка */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left: 25px;          /* отступ слева */\n"
"    top: 10px;          /* поднимаем текст, чтобы не пересекался с рамкой */\n"
"    /*background-color: white; /* фон под заголовком, чтобы \"перебить\" рамку */\n"
"    /*padding: 0 4px; */\n"
"    font-weight: 600;\n"
"}")
        self.grp_initial_data.setFlat(False)
        self.grp_initial_data.setObjectName("grp_initial_data")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.grp_initial_data)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 451, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.hlHistory = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.hlHistory.setContentsMargins(0, 0, 0, 0)
        self.hlHistory.setSpacing(15)
        self.hlHistory.setObjectName("hlHistory")
        self.lblHistory = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblHistory.setFont(font)
        self.lblHistory.setWordWrap(True)
        self.lblHistory.setObjectName("lblHistory")
        self.hlHistory.addWidget(self.lblHistory)
        self.leHistory = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.leHistory.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.leHistory.setObjectName("leHistory")
        self.hlHistory.addWidget(self.leHistory)
        self.btnHistory = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnHistory.setObjectName("btnHistory")
        self.hlHistory.addWidget(self.btnHistory)
        self.hlHistory.setStretch(0, 12)
        self.hlHistory.setStretch(1, 18)
        self.hlHistory.setStretch(2, 10)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.grp_initial_data)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 100, 451, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hlMaps = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hlMaps.setContentsMargins(0, 0, 0, 0)
        self.hlMaps.setSpacing(15)
        self.hlMaps.setObjectName("hlMaps")
        self.lblMaps = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMaps.setFont(font)
        self.lblMaps.setWordWrap(True)
        self.lblMaps.setObjectName("lblMaps")
        self.hlMaps.addWidget(self.lblMaps)
        self.leMaps = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_2)
        self.leMaps.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.leMaps.setObjectName("leMaps")
        self.hlMaps.addWidget(self.leMaps)
        self.btnMaps = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.btnMaps.setObjectName("btnMaps")
        self.hlMaps.addWidget(self.btnMaps)
        self.hlMaps.setStretch(0, 12)
        self.hlMaps.setStretch(1, 18)
        self.hlMaps.setStretch(2, 10)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.grp_initial_data)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(19, 150, 451, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.hlProperty = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.hlProperty.setContentsMargins(0, 0, 0, 0)
        self.hlProperty.setSpacing(15)
        self.hlProperty.setObjectName("hlProperty")
        self.lblProperty = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblProperty.setFont(font)
        self.lblProperty.setWordWrap(True)
        self.lblProperty.setObjectName("lblProperty")
        self.hlProperty.addWidget(self.lblProperty)
        self.leProperty = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_3)
        self.leProperty.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.leProperty.setObjectName("leProperty")
        self.hlProperty.addWidget(self.leProperty)
        self.btnProperty = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_3)
        self.btnProperty.setObjectName("btnProperty")
        self.hlProperty.addWidget(self.btnProperty)
        self.hlProperty.setStretch(0, 12)
        self.hlProperty.setStretch(1, 18)
        self.hlProperty.setStretch(2, 10)
        self.lblSavePath = QtWidgets.QLabel(parent=self.grp_initial_data)
        self.lblSavePath.setGeometry(QtCore.QRect(30, 240, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lblSavePath.setFont(font)
        self.lblSavePath.setObjectName("lblSavePath")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.grp_initial_data)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 280, 451, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.hlSave = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.hlSave.setContentsMargins(0, 0, 0, 0)
        self.hlSave.setSpacing(15)
        self.hlSave.setObjectName("hlSave")
        self.lblSave = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblSave.setFont(font)
        self.lblSave.setWordWrap(True)
        self.lblSave.setObjectName("lblSave")
        self.hlSave.addWidget(self.lblSave)
        self.leSave = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget_4)
        self.leSave.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.leSave.setObjectName("leSave")
        self.hlSave.addWidget(self.leSave)
        self.btnSave = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_4)
        self.btnSave.setObjectName("btnSave")
        self.hlSave.addWidget(self.btnSave)
        self.hlSave.setStretch(0, 12)
        self.hlSave.setStretch(1, 18)
        self.hlSave.setStretch(2, 10)

        self.retranslateUi(InitialDataPage)
        QtCore.QMetaObject.connectSlotsByName(InitialDataPage)

    def retranslateUi(self, InitialDataPage):
        _translate = QtCore.QCoreApplication.translate
        InitialDataPage.setWindowTitle(_translate("InitialDataPage", "Form"))
        self.grp_initial_data.setTitle(_translate("InitialDataPage", "Загрузка данных"))
        self.lblHistory.setText(_translate("InitialDataPage", "История работы скважин"))
        self.btnHistory.setText(_translate("InitialDataPage", "Выбрать файл"))
        self.lblMaps.setText(_translate("InitialDataPage", "Карты"))
        self.btnMaps.setText(_translate("InitialDataPage", "Выбрать папку"))
        self.lblProperty.setText(_translate("InitialDataPage", "Геолого-физическая характеристика"))
        self.btnProperty.setText(_translate("InitialDataPage", "Выбрать файл"))
        self.lblSavePath.setText(_translate("InitialDataPage", "Сохранение результатов"))
        self.lblSave.setText(_translate("InitialDataPage", "Путь сохранения результатов расчета"))
        self.btnSave.setText(_translate("InitialDataPage", "Выбрать папку"))
