# Form implementation generated from reading ui file 'start.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StartPage(object):
    def setupUi(self, StartPage):
        StartPage.setObjectName("StartPage")
        StartPage.resize(530, 530)
        self.txt_description = QtWidgets.QTextEdit(parent=StartPage)
        self.txt_description.setGeometry(QtCore.QRect(20, 30, 490, 480))
        self.txt_description.setStyleSheet("QTextEdit {\n"
"    background-color: rgb(250, 252, 253);\n"
"    border: 1px solid #d0dee9; \n"
"    padding: 10px;\n"
"    /*background: transparent; */\n"
"    /*border: none; */\n"
"}\n"
"\n"
"")
        self.txt_description.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.txt_description.setObjectName("txt_description")
        self.lbl_img = QtWidgets.QLabel(parent=StartPage)
        self.lbl_img.setGeometry(QtCore.QRect(300, 280, 180, 180))
        self.lbl_img.setText("")
        self.lbl_img.setPixmap(QtGui.QPixmap("../icons/АВНС_v.2.png"))
        self.lbl_img.setScaledContents(True)
        self.lbl_img.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_img.setObjectName("lbl_img")

        self.retranslateUi(StartPage)
        QtCore.QMetaObject.connectSlotsByName(StartPage)

    def retranslateUi(self, StartPage):
        _translate = QtCore.QCoreApplication.translate
        StartPage.setWindowTitle(_translate("StartPage", "Form"))
        self.txt_description.setHtml(_translate("StartPage", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">«АВНС»</span> — инструмент автоматизированного поиска перспективных зон и целей для формирования бизнес-кейсов уплотняющего бурения на зрелых месторождениях.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:700;\">ОСНОВНОЙ ФУНКЦИОНАЛ</span></p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Расчет оценочных карт:    </p>\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 0;\">\n"
"<li style=\" margin-top:2px; margin-bottom:2px; margin-left:45px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">оценка качества коллектора      </li>\n"
"<li style=\" margin-top:2px; margin-bottom:2px; margin-left:45px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">оценка потенциала      </li>\n"
"<li style=\" margin-top:2px; margin-bottom:2px; margin-left:45px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">оценка рисков      </li>\n"
"<li style=\" margin-top:2px; margin-bottom:2px; margin-left:45px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">индекс возможности бурения        </li></ul>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Выделение наиболее перспективных зон для бурения  </p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Построение карты проницаемости по фактическому фонду (РБ)  </p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Построение карты ОИЗ  </p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Построение карты обводненности  </p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Оценка ячеек Вороного  </p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Расчет радиусов дренирования/нагнетания  </p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Расстановка проектного фонда  </p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Расчет запускных параметров (РБ)  </p>\n"
"<p style=\" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Восстановление темпов падения  </p>\n"
"<p style=\" margin-top:2px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">– Расчет экономических показателей</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:36px; margin-bottom:36px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-style:italic; color:#666666;\">© 2025 IT-ННГ, БИР</span></p></body></html>"))
