# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 720)
        MainWindow.setMaximumSize(QtCore.QSize(800, 16777215))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"\n"
"    background-color: rgb(243, 245, 246);\n"
"\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.listWidget.setFont(font)
        self.listWidget.setToolTipDuration(-1)
        self.listWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.listWidget.setStyleSheet("QListWidget {\n"
"    background-color: rgb(243, 245, 246);\n"
"    font: 12pt \"Segoe UI\";\n"
"    border: 1px solid #d0dee9;\n"
"    border-bottom: none;  \n"
"}")
        self.listWidget.setLineWidth(1)
        self.listWidget.setMidLineWidth(0)
        self.listWidget.setAutoScrollMargin(16)
        self.listWidget.setProperty("showDropIndicator", True)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.listWidget.setIconSize(QtCore.QSize(18, 18))
        self.listWidget.setTextElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.listWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.listWidget.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(False)
        self.listWidget.setBatchSize(100)
        self.listWidget.setWordWrap(False)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/bi--folder-plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        item.setIcon(icon)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/bi--layers-half.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/ep--map-location.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        item.setIcon(icon2)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/drilling-rig.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        item.setIcon(icon3)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/water-drop (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        item.setIcon(icon4)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/free-icon-dollars-money-bag-50117.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        item.setIcon(icon5)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/ep--histogram.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        item.setIcon(icon6)
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 0, 0, 2, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.start_page = StartPageWidget()
        self.start_page.setObjectName("start_page")
        self.stackedWidget.addWidget(self.start_page)
        self.initial_data_page = InitialDataWidget()
        self.initial_data_page.setObjectName("initial_data_page")
        self.stackedWidget.addWidget(self.initial_data_page)
        self.mapping_page = MappingWidget()
        self.mapping_page.setObjectName("mapping_page")
        self.stackedWidget.addWidget(self.mapping_page)
        self.map_zone_page = DrillingZoneWidget()
        self.map_zone_page.setObjectName("map_zone_page")
        self.stackedWidget.addWidget(self.map_zone_page)
        self.well_params_page = WellParamsWidget()
        self.well_params_page.setObjectName("well_params_page")
        self.stackedWidget.addWidget(self.well_params_page)
        self.res_fluid_page = ResFluidWidget()
        self.res_fluid_page.setObjectName("res_fluid_page")
        self.stackedWidget.addWidget(self.res_fluid_page)
        self.economy_page = EconomyWidget()
        self.economy_page.setObjectName("economy_page")
        self.stackedWidget.addWidget(self.economy_page)
        self.result_page = ResultWidget()
        self.result_page.setObjectName("result_page")
        self.stackedWidget.addWidget(self.result_page)
        self.gridLayout.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 0, 10, -1)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCancel.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.btnCancel.setFont(font)
        self.btnCancel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btnCancel.setAutoFillBackground(False)
        self.btnCancel.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgb(230, 230, 230);  /* цвет кнопки */\n"
"    border-radius: 7px;\n"
"    font: 500 10pt \"Segoe UI\";\n"
"\n"
"}")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.Direction.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.btnCalc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalc.setMinimumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.btnCalc.setFont(font)
        self.btnCalc.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btnCalc.setAutoFillBackground(False)
        self.btnCalc.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: rgb(0, 112, 186);  /* цвет кнопки */\n"
"    border-radius: 7px;\n"
"    font: 600 10pt \"Segoe UI\";\n"
"    color: rgb(255, 255, 255);  /* цвет шрифта */\n"
"\n"
"}")
        self.btnCalc.setObjectName("btnCalc")
        self.horizontalLayout.addWidget(self.btnCalc)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout.setStretch(2, 3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    border: 1px solid #d0dee9;\n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 2, 0, 1, 2)
        self.gridLayout.setColumnMinimumWidth(0, 270)
        self.gridLayout.setColumnMinimumWidth(1, 530)
        self.gridLayout.setRowMinimumHeight(0, 530)
        self.gridLayout.setRowMinimumHeight(1, 60)
        self.gridLayout.setRowStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuBar.sizePolicy().hasHeightForWidth())
        self.menuBar.setSizePolicy(sizePolicy)
        self.menuBar.setMinimumSize(QtCore.QSize(0, 0))
        self.menuBar.setStyleSheet("QMenuBar {\n"
"        font-size: 9pt;      \n"
"        padding: 2px 4px;     /* вертикальные и горизонтальные отступы */\n"
"        background-color: rgb(240, 240, 240);\n"
"}\n"
"QMenuBar::item {\n"
"        spacing: 4px;         /* расстояние между пунктами меню */\n"
"        padding: 2px 4px;\n"
"}\n"
"\n"
"")
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(parent=self.menuBar)
        self.menu.setStyleSheet("")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.listWidget.setCurrentRow(-1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "АВНС"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Исходные данные"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Картопостроение"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Поиск зон бурения"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "Параметры скважин"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Свойства пласта и флюидов"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "Экономика"))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Результаты"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.btnCancel.setText(_translate("MainWindow", "Отменить"))
        self.btnCalc.setText(_translate("MainWindow", "Запустить расчёт"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action.setText(_translate("MainWindow", "О программе"))
from app.gui.widgets.drilling_zone import DrillingZoneWidget
from app.gui.widgets.economy import EconomyWidget
from app.gui.widgets.initial_data import InitialDataWidget
from app.gui.widgets.mapping import MappingWidget
from app.gui.widgets.res_fluid_params import ResFluidWidget
from app.gui.widgets.result import ResultWidget
from app.gui.widgets.start import StartPageWidget
from app.gui.widgets.well_params import WellParamsWidget
